"""Autogen — the list of every transform module.

Regenerated by ``scripts/regen_transforms_index.py``. Do NOT edit the fenced
block by hand.

Each module registers its ``BaseTransformer`` at import time by calling
``registry.register(...)``. ``load_all()`` walks the list once at package
import; the registry is then read-only.
"""

from __future__ import annotations

from importlib import import_module


# <!-- BEGIN autogen: transforms-index -->
ALL_MODULES = (
    "m3gast3gg.core.transforms.encoding.base32",
    "m3gast3gg.core.transforms.encoding.base64",
    "m3gast3gg.core.transforms.encoding.binary",
    "m3gast3gg.core.transforms.encoding.hex",
    "m3gast3gg.core.transforms.encoding.ternary",
    "m3gast3gg.core.transforms.format.reverse",
    "m3gast3gg.core.transforms.unicode.fullwidth",
    "m3gast3gg.core.transforms.unicode.zalgo",
    "m3gast3gg.core.transforms.visual.leetspeak",
)
# <!-- END autogen: transforms-index -->


def load_all() -> None:
    for m in ALL_MODULES:
        import_module(m)
