#!/usr/bin/env python3
"""Regenerate the tool-index block inside skill/reference docs from TOOL_SCHEMAS.

The MCP server owns the schemas (in `m3gast3gg/mcp/`); the skill docs need to
mirror them or the model reads a stale menu. Rather than hand-syncing, this
script imports the live `TOOL_SCHEMAS` and rewrites the section fenced by

    <!-- BEGIN autogen: tool index -->
    ...
    <!-- END autogen: tool index -->

Two output styles:

  bullets  — used in SKILL.md. Each family becomes an H3, tools become a
             bulleted list `- ``stegg_x`` — one-line description.`
  table    — used in REFERENCE.md. Each family becomes an H2, tools become
             rows of a small markdown table (name + one-line description).

Usage:
    python scripts/render_skill_tool_index.py --write
    python scripts/render_skill_tool_index.py --check
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from m3gast3gg.mcp import image, jailbreak, knowledge, meta, network, text, transforms, triage  # noqa: E402

BEGIN_FENCE = "<!-- BEGIN autogen: tool index -->"
END_FENCE = "<!-- END autogen: tool index -->"

FAMILIES: list[tuple[str, str, object]] = [
    ("triage", "Triage", triage),
    ("image", "Image", image),
    ("text", "Text / emoji", text),
    ("network", "Network", network),
    ("jailbreak", "Jailbreak / composers", jailbreak),
    ("transforms", "Text transforms", transforms),
    ("knowledge", "Knowledge (records + prose corpus)", knowledge),
    ("meta", "Meta / capabilities", meta),
]

TARGETS = [
    (REPO_ROOT / "skills" / "stegg-stego" / "SKILL.md", "bullets"),
    (REPO_ROOT / "skills" / "stegg-stego" / "REFERENCE.md", "table"),
]


def _one_line(description: str) -> str:
    """Collapse a schema description to one clean line for the index.

    Schema descriptions are frequently multi-line parenthesized strings with
    embedded newlines. For the index we want a compact one-liner — the first
    sentence when we can find one, otherwise the whole thing truncated.
    """
    collapsed = re.sub(r"\s+", " ", description).strip()
    # First-sentence trim: cut at a period followed by a space, keeping the
    # period. Skip if the first sentence is too short (likely an abbreviation).
    match = re.search(r"(.+?[.!?])\s+[A-Z]", collapsed)
    if match and len(match.group(1)) >= 30:
        return match.group(1)
    return collapsed


def _rows_for(module) -> list[tuple[str, str]]:
    schemas = getattr(module, "SCHEMAS", {})
    return sorted((name, _one_line(spec["description"])) for name, spec in schemas.items())


def render(style: str) -> str:
    """Render the full autogen block (fences included) in the requested style."""
    lines: list[str] = [BEGIN_FENCE, "<!-- Generated by scripts/render_skill_tool_index.py — do not edit by hand. -->"]

    for _key, heading, module in FAMILIES:
        rows = _rows_for(module)
        if not rows:
            continue
        lines.append("")
        if style == "bullets":
            lines.append(f"### {heading}")
            lines.append("")
            for name, desc in rows:
                lines.append(f"- `{name}` — {desc}")
        elif style == "table":
            lines.append(f"## {heading}")
            lines.append("")
            lines.append("| Tool | Description |")
            lines.append("| --- | --- |")
            for name, desc in rows:
                safe_desc = desc.replace("|", "\\|")
                lines.append(f"| `{name}` | {safe_desc} |")
        else:  # pragma: no cover — argparse restricts this
            raise ValueError(f"unknown style: {style}")

    lines.append("")
    lines.append(END_FENCE)
    return "\n".join(lines)


_FENCED_RE = re.compile(
    re.escape(BEGIN_FENCE) + r".*?" + re.escape(END_FENCE),
    re.DOTALL,
)


def apply(path: Path, style: str) -> tuple[str, str]:
    """Return (old_contents, new_contents) after substituting the autogen block."""
    old = path.read_text(encoding="utf-8")
    if BEGIN_FENCE not in old or END_FENCE not in old:
        raise SystemExit(
            f"{path}: missing autogen fences ({BEGIN_FENCE!r} / {END_FENCE!r}). "
            "Add them once by hand around the section to auto-generate."
        )
    new_block = render(style)
    new = _FENCED_RE.sub(lambda _m: new_block, old, count=1)
    return old, new


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Rewrite target files in place.")
    mode.add_argument("--check", action="store_true", help="Exit non-zero if files would change.")
    mode.add_argument("--stdout", choices=("bullets", "table"), help="Print one style to stdout.")
    args = parser.parse_args(argv)

    if args.stdout:
        print(render(args.stdout))
        return 0

    drift = 0
    for path, style in TARGETS:
        old, new = apply(path, style)
        if old == new:
            continue
        if args.check:
            drift += 1
            diff = difflib.unified_diff(
                old.splitlines(keepends=True),
                new.splitlines(keepends=True),
                fromfile=f"{path} (committed)",
                tofile=f"{path} (regenerated)",
            )
            sys.stdout.writelines(diff)
        else:
            path.write_text(new, encoding="utf-8")
            print(f"wrote {path}")

    if args.check and drift:
        print(
            f"\n{drift} file(s) out of sync with TOOL_SCHEMAS. "
            "Run: python scripts/render_skill_tool_index.py --write",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
