"""Parity tests for :mod:`f5_core._prng_stegg` against pinned JS output.

The fixture ``prng_stegg_vectors.json`` is regenerated by
``scripts/gen_f5_stegg_prng_vectors.js``.  If either the Python port or
the JS parameters change the fixture must be rerun and re-committed.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from f5_core._prng_stegg import StegPRNG, _pool_size


FIXTURE_PATH = Path(__file__).parent / "fixtures" / "f5" / "prng_stegg_vectors.json"


@pytest.fixture(scope="module")
def vec() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.fail(
            f"missing PRNG fixture at {FIXTURE_PATH}; "
            "regenerate with `node scripts/gen_f5_stegg_prng_vectors.js`"
        )
    return json.loads(FIXTURE_PATH.read_text())


def _prng_from(vec: dict) -> StegPRNG:
    return StegPRNG(bytes.fromhex(vec["key_hex"]), max_pixels=vec["max_pixels"])


def test_pool_size_matches_js(vec):
    """randPool = maxPixels * 4.125 bytes = maxPixels * 33 // 8."""
    expected = (vec["max_pixels"] * 33) // 8
    assert _pool_size(vec["max_pixels"]) == expected


def test_keystream_matches_js(vec):
    prng = _prng_from(vec)
    n = len(vec["keystream_first_bytes"])
    got = prng.pool[:n].tolist()
    assert got == vec["keystream_first_bytes"]


def test_permutation_matches_js(vec):
    prng = _prng_from(vec)
    got = prng.permute_indices(vec["perm_len"]).tolist()
    assert got == vec["permutation"]


def test_gamma_offset_matches_js(vec):
    prng = _prng_from(vec)
    n = len(vec["gamma_first_bytes"])
    gamma = prng.gamma_at(vec["perm_len"])
    assert gamma[:n].tolist() == vec["gamma_first_bytes"]


def test_permute_in_place_matches_permute_indices(vec):
    """f5get uses stegShuffle(coeff) which mutates the array.  For the
    identity input [0..n) it must produce the same permutation as the
    factory branch used by f5put.
    """
    prng = _prng_from(vec)
    n = vec["perm_len"]
    arr = np.arange(n, dtype=np.int32)
    prng.permute_in_place(arr)
    factory = prng.permute_indices(n)
    assert arr.tolist() == factory.tolist()


def test_empty_key_rejected():
    with pytest.raises(ValueError):
        StegPRNG(b"")


def test_str_key_rejected():
    with pytest.raises(TypeError):
        StegPRNG("password")  # type: ignore[arg-type]
